import { StyleSheet } from 'react-native';

export const tapRushStyles = StyleSheet.create({
    gameContainer: { flex: 1, backgroundColor: '#111827', paddingHorizontal: 16, paddingVertical: 10 },
    header: { marginBottom: 10 },
    title: { color: '#F9FAFB', fontSize: 34, fontWeight: '900' as any, letterSpacing: 0.5 },
    subtitle: { color: '#9CA3AF', fontSize: 14, marginTop: 2 },
    hud: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
        backgroundColor: '#1F2937',
        padding: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#374151',
    },
    hudItem: { color: '#E5E7EB', fontSize: 13, fontWeight: '700' as any },
    board: {
        flex: 1,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#374151',
        backgroundColor: '#0F172A',
        overflow: 'hidden',
        position: 'relative',
    },
    target: {
        width: 72,
        height: 72,
        borderRadius: 36,
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#EF4444',
        borderWidth: 4,
        borderColor: '#FCA5A5',
    },
    targetText: { color: '#FFF', fontWeight: '900' as any, fontSize: 17 },
    centerPanel: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 24 },
    panelTitle: { color: '#F9FAFB', fontWeight: '900' as any, fontSize: 28, textAlign: 'center' },
    panelText: { color: '#D1D5DB', textAlign: 'center', marginTop: 10, lineHeight: 20, fontSize: 15 },
    button: {
        marginTop: 22,
        backgroundColor: '#07283a',
        paddingHorizontal: 26,
        paddingVertical: 12,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#FFFFFF',
    },
    buttonText: { color: '#FFFFFF', fontWeight: '900' as any, fontSize: 16 },
    bottomDock: { paddingTop: 10, paddingBottom: 4, alignItems: 'center' },
    exitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1F2937',
        borderWidth: 1,
        borderColor: '#374151',
        borderRadius: 999,
        paddingVertical: 10,
        paddingHorizontal: 16,
    },
    exitIcon: { color: '#F9FAFB', fontSize: 16 },
    exitText: { color: '#F9FAFB', fontSize: 14, fontWeight: '700' as any },
});

export default tapRushStyles;
